<a href="https://colab.research.google.com/github/mike2ox/databreak-python-basic/blob/master/data_science_by_python_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/mike2ox/databreak-python-basic.git

fatal: destination path 'databreak-python-basic' already exists and is not an empty directory.


In [2]:
!ls

databreak-python-basic	sample_data


In [0]:
import pandas as pd

In [4]:
CCTV_Seoul = pd.read_csv("./databreak-python-basic/data/01. CCTV_in_Seoul.csv", encoding="utf-8")
CCTV_Seoul.head()

기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [5]:
CCTV_Seoul.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [6]:
CCTV_Seoul.columns[1]

'소계'

In [8]:
CCTV_Seoul.rename(columns={CCTV_Seoul.columns[0] : "구별"},inplace=True)
CCTV_Seoul.head()

구별    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [16]:
pop_Seoul = pd.read_excel("./databreak-python-basic/data/01. population_in_Seoul.xls", encoding="utf-8")
pop_Seoul.head()

기간  자치구       세대        인구  ...    인구.7    인구.8  세대당인구  65세이상고령자
0        기간  자치구       세대        합계  ...   등록외국인   등록외국인  세대당인구  65세이상고령자
1        기간  자치구       세대         계  ...      남자      여자  세대당인구  65세이상고령자
2  2017.1/4   합계  4202888  10197604  ...  128445  142191   2.36   1321458
3  2017.1/4  종로구    72654    162820  ...    4064    5167   2.11     25425
4  2017.1/4   중구    59481    133240  ...    4134    4794   2.09     20764

[5 rows x 14 columns]

In [25]:
pop_Seoul = pd.read_excel("./databreak-python-basic/data/01. population_in_Seoul.xls", 
                          header=2, usecols="B,D,G,J,N", encoding="utf-8")
pop_Seoul.head()

자치구           계        계.1       계.2   65세이상고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [0]:
pop_Seoul.rename(columns={pop_Seoul.columns[0] : "구별",
                          pop_Seoul.columns[1] : "인구수",
                          pop_Seoul.columns[2] : "한국인",
                          pop_Seoul.columns[3] : "외국인",
                          pop_Seoul.columns[4] : "고령자"}, inplace=True)

In [27]:
pop_Seoul.head()

구별         인구수        한국인       외국인        고령자
0   합계  10197604.0  9926968.0  270636.0  1321458.0
1  종로구    162820.0   153589.0    9231.0    25425.0
2   중구    133240.0   124312.0    8928.0    20764.0
3  용산구    244203.0   229456.0   14747.0    36231.0
4  성동구    311244.0   303380.0    7864.0    39997.0

In [0]:
import pandas as pd
import numpy as np

In [34]:
s = pd.Series([1,2,5,np.nan,11])
df = pd.DataFrame(np.random.randn(6,4), index=[0,1,2,3,4,5], columns=['A','B','C','D'])
df

A         B         C         D
0  0.897383  1.190330  1.645599 -0.491165
1  0.944161  1.471818  1.173361  0.602935
2 -1.360998  1.060107 -0.021163  1.812204
3 -1.083436  0.777541 -0.315092  0.994765
4 -0.293186  0.740573  1.496353  0.081556
5  0.799826  0.191610 -1.681636 -0.765283

In [41]:
print(df.values)
df.info()

[[ 0.89738317  1.19033044  1.64559935 -0.49116475]
 [ 0.94416082  1.47181838  1.17336092  0.6029354 ]
 [-1.36099849  1.06010663 -0.0211625   1.81220374]
 [-1.08343553  0.77754051 -0.31509236  0.99476455]
 [-0.29318615  0.7405733   1.49635273  0.08155558]
 [ 0.799826    0.19160979 -1.68163619 -0.76528297]]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [43]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.016042  0.905330  0.382904  0.372502
std    1.043745  0.442484  1.293969  0.963138
min   -1.360998  0.191610 -1.681636 -0.765283
25%   -0.885873  0.749815 -0.241610 -0.347985
50%    0.253320  0.918824  0.576099  0.342245
75%    0.872994  1.157774  1.415605  0.896807
max    0.944161  1.471818  1.645599  1.812204

In [52]:
print(df)
print(df.loc[1:3,'A':'C'])
print(df.iloc[1:4,0:3])

          A         B         C         D
0  0.897383  1.190330  1.645599 -0.491165
1  0.944161  1.471818  1.173361  0.602935
2 -1.360998  1.060107 -0.021163  1.812204
3 -1.083436  0.777541 -0.315092  0.994765
4 -0.293186  0.740573  1.496353  0.081556
5  0.799826  0.191610 -1.681636 -0.765283
          A         B         C
1  0.944161  1.471818  1.173361
2 -1.360998  1.060107 -0.021163
3 -1.083436  0.777541 -0.315092
          A         B         C
1  0.944161  1.471818  1.173361
2 -1.360998  1.060107 -0.021163
3 -1.083436  0.777541 -0.315092


1-4 pandas를 이용해서 CCTV와 인구현황 데이터 파악

In [56]:
print(CCTV_Seoul.sort_values(by="소계").head(6))
print(CCTV_Seoul.sort_values(by="소계", ascending=False).head(6))

     구별   소계  2013년도 이전  2014년  2015년  2016년
9   도봉구  485        238    159     42    386
12  마포구  574        314    118    169    379
17  송파구  618        529     21     68    463
24  중랑구  660        509    121    177    109
23   중구  671        413    190     72    348
5   광진구  707        573     78     53    174
     구별    소계  2013년도 이전  2014년  2015년  2016년
0   강남구  2780       1292    430    584    932
18  양천구  2034       1843    142     30    467
14  서초구  1930       1406    157    336    398
21  은평구  1873       1138    224    278    468
20  용산구  1624       1368    218    112    398
6   구로구  1561       1142    173    246    323


In [63]:
CCTV_Seoul["최근증가율"] = (CCTV_Seoul["2016년"] + CCTV_Seoul["2015년"]+CCTV_Seoul["2014년"])/ CCTV_Seoul["2013년도 이전"]*100
CCTV_Seoul.sort_values(by="최근증가율").head(6)

구별    소계  2013년도 이전  2014년  2015년  2016년      최근증가율
18   양천구  2034       1843    142     30    467  34.671731
13  서대문구   962        844     50     68    292  48.578199
20   용산구  1624       1368    218    112    398  53.216374
5    광진구   707        573     78     53    174  53.228621
14   서초구  1930       1406    157    336    398  63.371266
16   성북구  1464       1009     78    360    204  63.627354

In [62]:
CCTV_Seoul.sort_values(by="최근증가율").head(6)

구별    소계  2013년도 이전  2014년  2015년  2016년      최근증가율
18   양천구  2034       1843    142     30    467  34.671731
13  서대문구   962        844     50     68    292  48.578199
20   용산구  1624       1368    218    112    398  53.216374
5    광진구   707        573     78     53    174  53.228621
14   서초구  1930       1406    157    336    398  63.371266
16   성북구  1464       1009     78    360    204  63.627354